### ISSUE TITLE
Failing SSM with all configurations

### ISSUE THREAD

**Issue by rms1000watt** [variantdev/vals#11]
Hi, @mumoshu I'm super stoked SSM is in place. However, I'm unable to get it working from any of the configuration defined in the Readme. I took a quick look and didn't see any obvious bugs. I'll look again later to see if I can find anything.. But your help would be greatly appreciated. 🙏 

Here is my Helmfile:

```yaml
repositories:
  - name: "stable"
    url: "https://kubernetes-charts.storage.googleapis.com"

releases:
  - name: "fluent-bit"
    namespace: "kube-system"
    chart: "stable/fluent-bit"
    version: "2.0.5"
    atomic: true
    wait: true
    values:
    - filter:
        mergeJSONLog: false
    - backend:
        type: es
        es:
          host: "ref+ssm://pre0/pre1#/pre2/key0?region=us-east-1" # Err 1
          # host: "ref+ssm://pre0/pre1/pre2/#/key0?region=us-east-1" # Err 1
          # host: "ref+ssm://pre0/pre1/pre2/?region=us-east-1#/key0" # Err 2
          # host: "ref+ssm://pre0/pre1/pre2/?region=us-east-1#key0" # Err 2
          # host: "ref+ssm://pre0/pre1/pre2/key0?region=us-east-1" # Err 0
          # host: "ref+ssm://pre0/pre1/pre2/key0" # Err 2
          # host: "ref+ssm://pre0/pre1/pre2#/key0" # Err 2
          # host: "ref+ssm://pre0/pre1/pre2?region=us-east-1#/key0" # Err 2
          # host: "ref+ssm://pre0/pre1?region=us-east-1#/pre2/key0" # Err 2
```

Here are the error messages I get with each of these configurations:

Err 0:
```bash
in /darwin/path/to/helmfile/archive/fluent-bit.yml: expand ssm://......................................: get parameter: ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
```

Err 1:
```bash
in /darwin/path/to/helmfile/archive/fluent-bit.yml: expand ssm://......................................: ssm: get parameters by path: MissingRegion: could not find region configuration
```

Err 2:
```bash
in /darwin/path/to/helmfile/archive/fluent-bit.yml: expand ssm://......................................: ssm: get parameters by path: ValidationException: The parameter doesn't meet the parameter name requirements. The parameter name must begin with a forward slash "/". It can't be prefixed with \"aws\" or \"ssm\" (case-insensitive). It must use only letters, numbers, or the following symbols: . (period), - (hyphen), _ (underscore). Special characters are not allowed. All sub-paths, if specified, must use the forward slash symbol "/". Valid example: /get/parameters2-/by1./path0_.
```

I just can't crack it as it sits. 🤷‍♂
